MOROCCAN_CURRICULUM = {
    "primary": [
        {"name": "العربية", "code": "AR", "coefficient": 3.0},
        {"name": "الفرنسية", "code": "FR", "coefficient": 2.0},
        {"name": "الرياضيات", "code": "MATH", "coefficient": 3.0},
        {"name": "العلوم والتقنيات", "code": "SCI", "coefficient": 2.0},
        {"name": "التاريخ والجغرافيا", "code": "HIST", "coefficient": 1.0},
        {"name": "التربية الإسلامية", "code": "ISL", "coefficient": 1.0},
        {"name": "التربية المدنية", "code": "CIV", "coefficient": 1.0},
        {"name": "التربية الرياضية", "code": "PE", "coefficient": 1.0},
        {"name": "التربية التشكيلية والموسيقية", "code": "ART", "coefficient": 1.0},
        {"name": "الساقية الأمازيغية", "code": "AMZ", "coefficient": 0.5},
    ],
    "middle": [
        {"name": "العربية", "code": "AR", "coefficient": 3.0},
        {"name": "الفرنسية", "code": "FR", "coefficient": 3.0},
        {"name": "الإنجليزية", "code": "EN", "coefficient": 2.0},
        {"name": "الرياضيات", "code": "MATH", "coefficient": 3.0},
        {"name": "العلوم والتقنيات", "code": "SCI", "coefficient": 2.0},
        {"name": "التاريخ والجغرافيا", "code": "HIST", "coefficient": 1.5},
        {"name": "التربية الإسلامية", "code": "ISL", "coefficient": 1.0},
        {"name": "التربية المدنية", "code": "CIV", "coefficient": 0.5},
        {"name": "التربية الرياضية", "code": "PE", "coefficient": 1.0},
        {"name": "التربية التشكيلية والموسيقية", "code": "ART", "coefficient": 0.5},
        {"name": "الساقية الأمازيغية", "code": "AMZ", "coefficient": 0.5},
    ],
    "lycee_sciences": [
        {"name": "العربية", "code": "AR", "coefficient": 2.0},
        {"name": "الفرنسية", "code": "FR", "coefficient": 3.0},
        {"name": "الإنجليزية", "code": "EN", "coefficient": 2.0},
        {"name": "الرياضيات", "code": "MATH", "coefficient": 4.0},
        {"name": "الفيزياء والtpl", "code": "PHY", "coefficient": 4.0},
        {"name": "العلوم الطبيعية", "code": "BIO", "coefficient": 3.0},
        {"name": "التاريخ والجغرافيا", "code": "HIST", "coefficient": 1.0},
        {"name": "التربية الإسلامية", "code": "ISL", "coefficient": 1.0},
        {"name": "التربية المدنية", "code": "CIV", "coefficient": 0.5},
        {"name": "الساقية الأمازيغية", "code": "AMZ", "coefficient": 0.5},
    ],
    "lycee_lettres": [
        {"name": "العربية", "code": "AR", "coefficient": 4.0},
        {"name": "الفرنسية", "code": "FR", "coefficient": 3.0},
        {"name": "الإنجليزية", "code": "EN", "coefficient": 2.0},
        {"name": "الرياضيات", "code": "MATH", "coefficient": 2.0},
        {"name": "التاريخ والجغرافيا", "code": "HIST", "coefficient": 3.0},
        {"name": "الفلسفة", "code": "PHI", "coefficient": 2.0},
        {"name": "العلوم الطبيعية", "code": "BIO", "coefficient": 1.0},
        {"name": "التربية الإسلامية", "code": "ISL", "coefficient": 1.0},
        {"name": "التربية المدنية", "code": "CIV", "coefficient": 0.5},
        {"name": "الساقية الأمازيغية", "code": "AMZ", "coefficient": 0.5},
    ],
}
